---
title: "Carte musée"
author: "Clément Caillard"
date: "01/03/2021"
output: html_document
---

```{r}
library(leaflet)
library(tidyverse)
# setwd("C:/Users/caill/Dropbox/M1/S2/R/VISUDATA/Projet/VisuMarineClement")
# musee <- read.table('musee.csv', sep=",", header=T)
```
```{r}
testurl <- function(texte){
  for (chaine in strsplit(texte, " ")[[1]]){
    if(grepl("^http" ,chaine)){return(chaine)}
    if(grepl("^www.",chaine)){return(paste("http://", chaine, sep=""))}
  }
  return(F)
}

fpopup <- function(rdt){
  rdt <-  data.frame(t(rdt))
  popup = "
  <head>
 <style>
 .leaflet-container a{
  text-decoration:none;
  margin-bottom:1;}
    a:hover{color:Black}

h4{color:#0078A8}
#txt{margin-left:5px;}
#ad, #txt{
    display: inline-block;
    vertical-align: top;
    margin-bottom: 0;}
.leaflet-container p{color:#293133;}
 </style>
</head><body>"
  title = paste('<h4>', as.character(rdt$name), "</h4>")
  if (testurl(as.character(rdt$sitweb)) != F){
    popup = popup %>% paste("<a href='", testurl(as.character(rdt$sitweb)), "'>", title, "</a>", sep ="")
  }else{
    popup = popup %>% paste(title)
  } 
  popup = popup %>% paste('<p id="ad"><strong>Adresse:</strong></p>')
  rdt = unite(rdt, "ad", number, street, sep=' ',na.rm = T)
  if(is.na(rdt$postal_code)){
    popup = popup %>% paste('<p id="txt">', rdt$ad , "<br>", rdt$city,"</p>", sep="")
  }else{
    popup = popup %>% paste('<p id="txt">', rdt$ad , "<br>", rdt$postal_code, " ", rdt$city,"</p>", sep="")
  }
  popup = popup %>% paste('<p><strong>Téléphone: </strong>', rdt$telephone1, "</p>", sep="")
  popup = popup %>% paste('<p><strong>Total visiteur en 2018: </strong>', rdt$total.2018, "</p></body>", sep="")
  return(popup)
}
```

```{r}
if (!(require(jsonlite))) install.packages("jsonlite")
mygeocode <- function(adresses){
  # adresses est un vecteur contenant toutes les adresses sous forme de chaine de caracteres
  nominatim_osm <- function(address = NULL){
    ## details: http://wiki.openstreetmap.org/wiki/Nominatim
    ## fonction nominatim_osm proposée par D.Kisler
    if(suppressWarnings(is.null(address)))  return(data.frame())
    tryCatch(
      d <- jsonlite::fromJSON(
        gsub('\\@addr\\@', gsub('\\s+', '\\%20', address),
             'http://nominatim.openstreetmap.org/search/@addr@?format=json&addressdetails=0&limit=1')
      ), error = function(c) return(data.frame())
    )
    if(length(d) == 0) return(data.frame())
    return(c(as.numeric(d$lon), as.numeric(d$lat)))
  }
  tableau <- t(sapply(adresses,nominatim_osm))
  colnames(tableau) <- c("lon","lat")
  return(tableau)
}
```


